--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ClickedTran/libScriptAPI
build-by-default: false
branches:
- Master
projects:
  libScriptAPI:
    path: ""
    model: virion
    type: library
...
